lib: add missing permissions for patchwork_covercomment_id_seq
Grants UPDATE and SELECT privileges on patchwork_covercomment_id_seq table
for user 'nobody' to fix the following exception when cover comments
are being parsed:
django.db.utils.ProgrammingError: permission denied for sequence
  patchwork_covercomment_id_seq

Signed-off-by: Ali Alnubani <alialnu@nvidia.com>