bin/pwclient: fix spurious except catch
The 'with' statement does not start an exception block like 'try' would,
so we get an error executing pwclient:

      File "/home/ymorin/bin/pwclient", line 300
        except IOError:
             ^
    SyntaxError: invalid syntax

Instead, don't try to catch any exception: any failure will be
propagated back up the stack and eventually cause an abort, which is
anyway what the except clause was trying to do.

Signed-off-by: "Yann E. MORIN" <yann.morin.1998@free.fr>
Cc: Stephen Finucane <stephenfinucane@hotmail.com>
Reviewed-by: Stephen Finucane <stephenfinucane@hotmail.com>