lib: add missing permissions for patchwork_cover_id_seq
Grants UPDATE and SELECT privileges on patchwork_cover_id_seq table
for user 'nobody' to fix the following exception when cover letters
are being parsed:
django.db.utils.ProgrammingError: permission denied for sequence
  patchwork_cover_id_seq

Signed-off-by: Ali Alnubani <alialnu@nvidia.com>