lib: add missing permissions for patchwork_comment_id_seq
Grants UPDATE and SELECT privileges on patchwork_comment_id_seq table
for web and mail users to fix the following exception when comments
are parsed:
django.db.utils.ProgrammingError: permission denied for sequence
  patchwork_comment_id_seq

Fixes: 5b53f46def5f ("lib: fix table names")

Signed-off-by: Ali Alnubani <alialnu@nvidia.com>
(cherry picked from commit f7bb805037d7d8710a0b025536616ef9cdfd4cef)