pwclient fix for handling messages with UTF-8
pwclient works fine viewing utf-8 messages, if you don't try to redirect stdout.

However, if you do things like pwclient view 5063 >/tmp/patch, it fails
due to the weird character handling logic in python:

Traceback (most recent call last):
  File "/usr/local/bin/pwclient", line 446, in ?
    main()
  File "/usr/local/bin/pwclient", line 411, in main
    print s
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe1' in position 249: ordinal not in range(128)

Signed-off-by: Mauro Carvalho Chehab <mchehab@redhat.com>
Signed-off-by: Jeremy Kerr <jk@ozlabs.org>